name: Poetry Build and Deploy 

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
  
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
        
      - name: Install dependencies
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          cd /home/runner/work/lab-python-ci/with/
          poetry install
  
      - name: Build package
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry build
  
      - name: Publish package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry publish --no-interaction --username __token__ --password $POETRY_PYPI_TOKEN_PYPI
  