name: Cron Job

on:
  schedule:
    - cron: '57 3 * * 0' # Executa toda sexta-feira às 8 da manhã (UTC)

jobs:
  send-email-if-closest-friday:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Get current date and calculate closest Friday to 15th
        id: closest-friday
        run: |
          TARGET_DAY=15
          CURRENT_YEAR=$(date +%Y)
          CURRENT_MONTH=$(date +%m)
          TARGET_DATE=$(date -d "$CURRENT_YEAR-$CURRENT_MONTH-$TARGET_DAY" +%Y-%m-%d)
          
          TARGET_FRIDAY=$(date -d "$TARGET_DATE -$(($(date -d $TARGET_DATE +%u) - 5)) days" +%Y-%m-%d)
          TARGET_FRIDAY_PLUS_7=$(date -d "$TARGET_FRIDAY + 7 days" +%Y-%m-%d)
          TARGET_FRIDAY_MINUS_7=$(date -d "$TARGET_FRIDAY - 7 days" +%Y-%m-%d)
          
          CURRENT_DATE=$(date +%Y-%m-%d)
          if [[ "$CURRENT_DATE" == "$TARGET_FRIDAY" ]] || [[ "$CURRENT_DATE" == "$TARGET_FRIDAY_PLUS_7" ]] || [[ "$CURRENT_DATE" == "$TARGET_FRIDAY_MINUS_7" ]]; then
            echo "closest_friday=true" >> $GITHUB_ENV
          else
            echo "closest_friday=false" >> $GITHUB_ENV
          fi

      - name: Send Email
        run: |
          if [[ $closest_friday == "true" ]]; then
            echo "Sending email..."
            # Comando para enviar email
          else
            echo "Not sending email..."
          fi
